spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/BankMega
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
